version: '3.7'

services:
  pocketbase:
    image: augustodelg/pocketbase
    ports:
      - 8090:8090
    volumes:
      - pocketbase-data:/pb_data
      - ./public:/pb_public
      - ./migrations:/pb_migrations

volumes:
  pocketbase-data: